name: palette_master
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.1
  
  # Routing
  go_router: ^14.8.1
  
  # UI
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.8
  flutter_vector_icons: ^2.0.0
  
  # Utils
  equatable: ^2.0.5
  shared_preferences: ^2.2.1
  audioplayers: ^6.4.0
  vibration: ^3.1.3
  url_launcher: ^6.3.1
  
  # Color utilities
  tinycolor2: ^3.0.1

  # Firebase
  firebase_core: ^3.12.1
  showcaseview: ^4.0.1

  # Physics
  # forge2d: ^0.14.0
  flame: ^1.27.0
  just_audio: ^0.10.0
  flame_forge2d: ^0.18.3+1

  firebase_analytics: ^11.4.4

  # ads
  google_mobile_ads: ^5.2.0
  flutter_dotenv: ^5.2.1
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  riverpod_generator: ^2.3.2
  build_runner: ^2.4.6
  go_router_builder: ^2.3.1

flutter:

  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/
    - assets/audio/
    - assets/audio/bgm/
    - assets/audio/sfx/
